# Setup
title:  Bretonics
tagline:
email:  me@andresbreton.com
description: > # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
url: "http://bretonics.github.com" # the base hostname & protocol for your site
twitter_username: breton89
github_username:  bretonics
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Andres Breton
  url:        http://andresbreton.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: redcarpet
